logging:
  level:
    root: INFO
---
server:
  port: 8080
  servlet:
    context-path: /baseServices
---
keycloak:
  enabled: true
  bearer-only: true
  #auth-server-url: https://portal.ecuasanitas.com/auth-test
  #desarrollo externo
  auth-server-url: https://portal.ecuasanitas.com/auth-test
  #desarrollo interno
  #auth-server-url: http://192.168.40.151:8080/auth

  resource: farmaenlace-ws
  realm: xtn
  public-client: true
  principal-attribute: preferred_username
  # credentials:
  # secret: 123
  use-resource-role-mappings: false
  allowAnyHostname: true
  #ssl-required: external
  realm-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAntXAHG+gLv6qcua5LWpHNe08lZmrLGg2rDHWd4u6PDkDGhpdu8lRUSejfnU4uSlo9t9bbVNPBhGX/cXFGAR27f+mNUHtGPWP6Kejr5q77DgUhJ7kRTjxuoh75x/XUq99JB7+9Kyy5w8GqwDDhs+JVzjLoIZgCCtcqWdJNEEQJGgnaJBkt+s778qSL+MYG5zHOs2NNHXY33sIl3YS/QbLZRYkHubGVb9WC3KgyeGmqryUa6GQLJ1FjXR4nbh6hEXKHCO9I3bpqW/i3yYWBKc6oWErCL2Zu6NeZ26NthJ+8fuvN1Wd7tR+M2Za9DS5LLBYDe1M06gogctd0tGAX6CUwwIDAQAB
  truststore: classpath:certs/SSLKeystore.jks
  truststore-password: ecuasanitas2019
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.40.24:1521/bdd1.ecuasanitas.com
    username: NOVO
    password: NOVO
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      #connectionTestQuery: CALL NOW()
  jpa:
    showSql: true
    properties:
      format_sql: false
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        #        dialect: org.hibernate.dialect.MariaDB103Dialect
        id:
          batch_versioned_data: true
          new_generator_mappings: false # true for increment by 50 or (allocationSize property in mapping), false for increment one by one
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false


---
springdoc:
  springdoc:
    packagesToScan: com.base.controller
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true
